const data = [
    {
        id:1,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary"
        ,starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : false,
    },
    {
        id:2,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:3,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:4,
        from:"Udemy",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"10:24pm",
        type:"promotion",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:5,
        from:"Google",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"Nov3",
        type:"promotion",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : false,
    },
    {
        id:6,
        from:"Microsoft",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"Oct31",
        type:"promotion",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:7,
        from:"Facebook",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"10:24pm",
        type:"social",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : false,
    },
    {
        id:8,
        from:"Instagram",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"Nov3",
        type:"social",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:9,
        from:"Twitter",
        message:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing",
        time:"Oct31",
        type:"social",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:10,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:11,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:12,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:13,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:14,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:15,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:16,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:17,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:18,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:19,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:20,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:21,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:22,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:23,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:24,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:25,
        from:"Google",
        message:"Welcome to gmail.Hope you enjoy using it.",
        time:"3:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:26,
        from:"Thae Lay",
        message:"Hello Oppa koko yay ta nay kone pyit loe htar htl hay",
        time:"1:13am",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
    {
        id:27,
        from:"Udemy",
        message:"jjfkdhsgaijereitnfja gaijhfuaidsufhi hgiahkfjduhgirjwb jithajfdjhiaheijhtajbjahtlk",
        time:"9:24pm",
        type:"primary",
        starred : false,
        delete:false,
        important:false,
        spam:false,
        isCheck : false,
        isRead : true,
    },
];

export default data